export const mockDriver = {
  id: "1",
  full_name: "Jean Dupont",
  phone: "+33 6 12 34 56 78",
  whatsapp: "+33 6 12 34 56 78",
  email: "jean.dupont@example.com",
  city: "Paris",
  public_slug: "jean-dupont",
  bio: "Chauffeur privé depuis 5 ans, je vous accompagne dans tous vos déplacements en Île-de-France avec professionnalisme et discrétion.",
  vehicle_brand: "Mercedes-Benz",
  vehicle_model: "Classe E",
  vehicle_color: "Noir",
  vehicle_seats: 3,
  vehicle_options: ["Wifi", "Bouteille d'eau", "Chargeur tel", "Siège auto sur demande"],
  service_zones: ["Paris", "Île-de-France", "Aéroports (CDG, Orly)"],
  is_available: true,
  current_zone: "Paris Centre",
  available_until: "18:00",
};

export const mockStats = {
  today_requests: 5,
  confirmed_bookings: 3,
  private_clients: 42,
  estimated_revenue: 285,
};

export const mockBookings = [
  {
    id: "b1",
    date: "2024-05-04",
    time: "14:30",
    pickup: "Aéroport CDG - Terminal 2E",
    dropoff: "Hôtel Ritz, Paris",
    client_name: "Sophie Martin",
    client_phone: "+33 6 98 76 54 32",
    status: "pending", // pending, confirmed, completed, cancelled
    price: 85,
  },
  {
    id: "b2",
    date: "2024-05-04",
    time: "17:00",
    pickup: "Gare de Lyon",
    dropoff: "La Défense",
    client_name: "Marc Dubreuil",
    client_phone: "+33 6 11 22 33 44",
    status: "confirmed",
    price: 65,
  },
  {
    id: "b3",
    date: "2024-05-05",
    time: "09:00",
    pickup: "Versailles",
    dropoff: "Aéroport Orly",
    client_name: "Emma Leroy",
    client_phone: "+33 6 55 44 33 22",
    status: "confirmed",
    price: 90,
  },
];

export const mockClients = [
  {
    id: "c1",
    name: "Sophie Martin",
    phone: "+33 6 98 76 54 32",
    email: "sophie.m@example.com",
    trips_count: 12,
    tag: "VIP",
    last_trip: "2024-04-28",
    notes: "Aime écouter de la musique classique. Toujours de l'eau gazeuse.",
  },
  {
    id: "c2",
    name: "Marc Dubreuil",
    phone: "+33 6 11 22 33 44",
    email: "marc.d@example.com",
    trips_count: 5,
    tag: "Régulier",
    last_trip: "2024-05-01",
    notes: "Voyages d'affaires. Parle peu.",
  },
  {
    id: "c3",
    name: "Emma Leroy",
    phone: "+33 6 55 44 33 22",
    email: "emma.l@example.com",
    trips_count: 1,
    tag: "Nouveau",
    last_trip: "2024-04-15",
    notes: "",
  },
  {
    id: "c4",
    name: "Thomas Dubois",
    phone: "+33 6 77 88 99 00",
    email: "thomas.d@example.com",
    trips_count: 8,
    tag: "Régulier",
    last_trip: "2024-03-20",
    notes: "Résidant à Neuilly.",
  },
];

export const mockRoutes = [
  {
    id: "r1",
    title: "Transfert CDG",
    pickup: "Paris (Intra-muros)",
    dropoff: "Aéroport Charles de Gaulle (CDG)",
    price: 75,
    description: "Forfait fixe pour tout transfert de Paris vers l'aéroport CDG.",
    active: true,
  },
  {
    id: "r2",
    title: "Transfert Orly",
    pickup: "Paris (Intra-muros)",
    dropoff: "Aéroport d'Orly",
    price: 65,
    description: "Forfait fixe pour tout transfert de Paris vers l'aéroport d'Orly.",
    active: true,
  },
  {
    id: "r3",
    title: "Mise à disposition (Demi-journée)",
    pickup: "Paris",
    dropoff: "Paris / IDF",
    price: 300,
    description: "Mise à disposition du véhicule et du chauffeur pour 4 heures (100km max).",
    active: false,
  },
];
